#!/bin/bash
# Resume Print Tool - Klipper Installer
# Installs resume_print.py and generates a Klipper config with correct paths

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Resume Print Tool - Klipper Installer ==="
echo ""

# Detect Klipper config and gcodes directories
if [ -d "$HOME/printer_data/config" ]; then
    CONFIG_DIR="$HOME/printer_data/config"
    GCODES_DIR="$HOME/printer_data/gcodes"
elif [ -d "$HOME/klipper_config" ]; then
    CONFIG_DIR="$HOME/klipper_config"
    GCODES_DIR="$HOME/gcode_files"
else
    echo "ERROR: Could not find Klipper config directory."
    echo "Set it manually: CONFIG_DIR=/path/to/config bash install.sh"
    exit 1
fi

SCRIPTS_DIR="$CONFIG_DIR/scripts"
INSTALL_PATH="$SCRIPTS_DIR/resume_print.py"
CFG_OUTPUT="$CONFIG_DIR/resume_print.cfg"

echo "Config directory : $CONFIG_DIR"
echo "Gcodes directory : $GCODES_DIR"
echo "Script install   : $INSTALL_PATH"
echo ""

# Install script
mkdir -p "$SCRIPTS_DIR"
cp "$SCRIPT_DIR/resume_print.py" "$INSTALL_PATH"
chmod +x "$INSTALL_PATH"
echo "✓ Installed resume_print.py to $INSTALL_PATH"

# Check for gcode_shell_command extra
SHELL_CMD_EXTRA="$HOME/klipper/klippy/extras/gcode_shell_command.py"
if [ ! -f "$SHELL_CMD_EXTRA" ]; then
    echo ""
    echo "⚠️  gcode_shell_command.py not found at $SHELL_CMD_EXTRA"
    echo "   Installing via KIAUH resource..."
    curl -fsSL -o "$SHELL_CMD_EXTRA" \
        "https://raw.githubusercontent.com/dw-0/kiauh/master/resources/gcode_shell_command.py" \
        && echo "✓ Installed gcode_shell_command.py" \
        || echo "   FAILED - install manually via KIAUH > Extensions, then re-run this script"
fi

# Generate resume_print.cfg with correct paths baked in
cat > "$CFG_OUTPUT" << EOF
# Resume Print Tool - Klipper Configuration
# Generated by install.sh on $(date)
#
# Add to printer.cfg:
#   [include resume_print.cfg]
#
# Then restart Klipper and run from Mainsail/Fluidd console:
#   GENERATE_RESUME GCODE_FILE=myprint.gcode HEIGHT=12.22
#
# Parameters:
#   GCODE_FILE    - filename in your gcodes folder (required)
#   HEIGHT        - Z height to resume from in mm (required)
#   LAYER_HEIGHT  - layer height in mm (default: 0.3)
#   BED_TEMP      - bed temperature override, 0 = auto-detect (default: 0)
#   HOTEND_TEMP   - hotend temperature override, 0 = auto-detect (default: 0)

[gcode_shell_command resume_print_cmd]
command: python3 $INSTALL_PATH
timeout: 60.0
verbose: True

[gcode_macro GENERATE_RESUME]
description: Generate a resume gcode file for a failed print
gcode:
    {% set gcode_file = params.GCODE_FILE|default("")|string %}
    {% set height = params.HEIGHT|default(0.0)|float %}
    {% set layer_height = params.LAYER_HEIGHT|default(0.3)|float %}
    {% set bed_temp = params.BED_TEMP|default(0)|int %}
    {% set hotend_temp = params.HOTEND_TEMP|default(0)|int %}

    {% if gcode_file == "" %}
        { action_raise_error("GCODE_FILE is required, e.g. GENERATE_RESUME GCODE_FILE=myprint.gcode HEIGHT=12.22") }
    {% elif height == 0.0 %}
        { action_raise_error("HEIGHT is required, e.g. GENERATE_RESUME GCODE_FILE=myprint.gcode HEIGHT=12.22") }
    {% else %}
        {% set input_path = "$GCODES_DIR/" + gcode_file %}
        {% set base = input_path + " --height " + height|string + " --layer-height " + layer_height|string %}
        {% if bed_temp > 0 and hotend_temp > 0 %}
            RUN_SHELL_COMMAND CMD=resume_print_cmd PARAMS="{base} --bed-temp {bed_temp} --hotend-temp {hotend_temp}"
        {% elif bed_temp > 0 %}
            RUN_SHELL_COMMAND CMD=resume_print_cmd PARAMS="{base} --bed-temp {bed_temp}"
        {% elif hotend_temp > 0 %}
            RUN_SHELL_COMMAND CMD=resume_print_cmd PARAMS="{base} --hotend-temp {hotend_temp}"
        {% else %}
            RUN_SHELL_COMMAND CMD=resume_print_cmd PARAMS="{base}"
        {% endif %}
        { action_respond_info("Generating resume file for %s at Z=%.2fmm - refresh file list when done" % (gcode_file, height)) }
    {% endif %}
EOF

echo "✓ Generated $CFG_OUTPUT"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "1. Add to your printer.cfg:"
echo "      [include resume_print.cfg]"
echo ""
echo "2. Restart Klipper (FIRMWARE_RESTART or via web UI)"
echo ""
echo "3. In Mainsail/Fluidd console:"
echo "      GENERATE_RESUME GCODE_FILE=myprint.gcode HEIGHT=12.22"
echo ""
echo "   Optional overrides:"
echo "      LAYER_HEIGHT=0.3  BED_TEMP=75  HOTEND_TEMP=265"
echo ""
echo "4. The *_resumed.gcode file will appear in your files list - start it to resume the print"
